apiVersion: v1
kind: Service
metadata:
  name: news-app-svc
  namespace: news-app-ns
  labels:
    app: news-app-svc
    lang: all #select all languages
  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: news-app