apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: news-app-python
  namespace: news-app-ns
  labels:
    app: news-app
    lang: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-app
  template:
    metadata:
      labels:
        app: news-app
        lang: python
    spec:
      containers:
        - image: balanus/newsapp:python-v1
          name: news-app
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          ports:
            - containerPort: 5000
              name: news-app
