apiVersion: v1
kind: Service
metadata:
  name: fortune-app-svc-nodejs
  namespace: fortune-app-ns
  labels:
    app: fortune-app-svc
    lang: nodejs

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: fortune-app
    lang: nodejs