apiVersion: v1
kind: Service
metadata:
  name: news-app-svc-nodejs
  namespace: news-app-ns
  labels:
    app: news-app-svc
    lang: nodejs

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: news-app
    lang: nodejs